using Grinding.Shared.Models;
using Grinding.Shared.Dtos;
using Grinding.Services.Data; // For GrindingDbContext
using Microsoft.EntityFrameworkCore; // For EF Core extension methods like ToListAsync, FirstOrDefaultAsync
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Grinding.Services
{
    public class OperationalService : IOperationalService
    {
        private readonly GrindingDbContext _context;

        public OperationalService(GrindingDbContext context)
        {
            _context = context;
        }

        public async Task<IEnumerable<OperationalRestResponseDTO>> GetAllOperationalDataAsync()
        {
            // It's good practice to project to DTOs in the query to fetch only necessary data.
            return await _context.OperationalData
                .AsNoTracking() // Good for read-only queries, improves performance.
                .Select(op => new OperationalRestResponseDTO // Use Response DTO
                {
                    Id = op.Id, // Server-generated Id
                    ClientDbId = op.ClientDbId,
                    ClientId = op.ClientId,
                    //TableName = "Operational", // Optional: if needed in response
                    Date = op.Date,
                    EventId = op.EventId,
                    Description = op.Description,
                    Object = op.Object,
                    Operator = op.Operator,
                    ServerTimestamp = op.ServerTimestamp,
                    ChangeCounter = op.ChangeCounter
                })
                .ToListAsync();
        }

        public async Task<OperationalRestResponseDTO?> GetOperationalDataByIdAsync(int serverId) // Parameter is the server's primary key
        {
            var operationalEntity = await _context.OperationalData
                .AsNoTracking()
                .FirstOrDefaultAsync(op => op.Id == serverId); // Query by the entity's actual PK 'Id'

            if (operationalEntity == null)
            {
                return null;
            }

            // Map the found entity to a DTO
            return new OperationalRestResponseDTO // Use Response DTO
            {
                Id = operationalEntity.Id, // Server-generated Id
                ClientDbId = operationalEntity.ClientDbId,
                ClientId = operationalEntity.ClientId,
                //TableName = "Operational", // Optional
                Date = operationalEntity.Date,
                EventId = operationalEntity.EventId,
                Description = operationalEntity.Description,
                Object = operationalEntity.Object,
                Operator = operationalEntity.Operator,
                ServerTimestamp = operationalEntity.ServerTimestamp,
                ChangeCounter = operationalEntity.ChangeCounter
            };
        }

        public async Task<OperationalRestResponseDTO> CreateOperationalDataAsync(OperationalRestPostRequestDTO operationalDto)
        {
            var operationalEntity = new Operational
            {
                ClientDbId = operationalDto.ClientDbId, // DTO property is now ClientDbId
                ClientId = operationalDto.ClientId ?? string.Empty, // Ensure not null if model requires
                Date = operationalDto.Date,
                EventId = operationalDto.EventId,
                Description = operationalDto.Description ?? string.Empty, // Ensure not null if model requires
                Object = operationalDto.Object, // Already nullable in DTO and Entity
                Operator = operationalDto.Operator ?? string.Empty, // Ensure not null if model requires
                // ServerTimestamp and ChangeCounter will use their default values or be set by DB
                // The entity's 'Id' (primary key) will be auto-generated by the database
            };

            _context.OperationalData.Add(operationalEntity);
            await _context.SaveChangesAsync();

            // Return the newly created entity mapped to a Response DTO
            return new OperationalRestResponseDTO
            {
                Id = operationalEntity.Id, // Include the server-generated Id
                ClientDbId = operationalEntity.ClientDbId,
                ClientId = operationalEntity.ClientId,
                Date = operationalEntity.Date,
                EventId = operationalEntity.EventId,
                Description = operationalEntity.Description,
                Object = operationalEntity.Object,
                Operator = operationalEntity.Operator,
                ServerTimestamp = operationalEntity.ServerTimestamp,
                ChangeCounter = operationalEntity.ChangeCounter
                // TableName can be set if desired
            };
        }

        public async Task<IEnumerable<OperationalRestResponseDTO>> CreateOperationalDataBatchAsync(IEnumerable<OperationalRestPostRequestDTO> operationalDtos)
        {
            var newOperationalEntities = new List<Operational>();
            foreach (var operationalDto in operationalDtos)
            {
                newOperationalEntities.Add(new Operational
                {
                    ClientDbId = operationalDto.ClientDbId, // DTO property is now ClientDbId
                    ClientId = operationalDto.ClientId ?? string.Empty,
                    Date = operationalDto.Date,
                    EventId = operationalDto.EventId,
                    Description = operationalDto.Description ?? string.Empty,
                    Object = operationalDto.Object,
                    Operator = operationalDto.Operator ?? string.Empty
                });
            }

            if (!newOperationalEntities.Any())
            {
                return Enumerable.Empty<OperationalRestResponseDTO>();
            }

            await _context.OperationalData.AddRangeAsync(newOperationalEntities);
            await _context.SaveChangesAsync();

            // Map the newly created entities (now with server-generated IDs) back to ResponseDTOs
            return newOperationalEntities.Select(entity => new OperationalRestResponseDTO
            {
                Id = entity.Id,
                ClientDbId = entity.ClientDbId,
                ClientId = entity.ClientId,
                Date = entity.Date,
                EventId = entity.EventId,
                Description = entity.Description,
                Object = entity.Object,
                Operator = entity.Operator,
                ServerTimestamp = entity.ServerTimestamp,
                ChangeCounter = entity.ChangeCounter
            }).ToList();
        }
    }
}